version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_prueba
    restart: always
    environment:
      POSTGRES_DB: my_db_productos
      POSTGRES_USER: thiago
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

