name: Deploy SAM Application

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Install esbuild globally
        run: npm install -g esbuild

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        run: |
          sam deploy \
            --stack-name productos-api \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --parameter-overrides \
              DBHost=${{ secrets.DB_HOST }} \
              DBPort=${{ secrets.DB_PORT }} \
              DBUsername=${{ secrets.DB_USERNAME }} \
              DBPassword=${{ secrets.DB_PASSWORD }} \
              DBName=${{ secrets.DB_NAME }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
