name: Deploy SAM Application

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Set up Python (for pip)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Install dependencies
        working-directory: ./payments
        run: npm install

      - name: Install esbuild globally
        run: npm install -g esbuild

      - name: Build SAM application
        run: sam build

      - name: Desplegar con SAM
        run: sam deploy --config-file samconfig.toml --no-confirm-changeset --no-fail-on-empty-changeset
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
